index:
    path: /
    controller: App\Controller\HomeController::index
user:
    path: /user
    controller: App\Controller\UserController::index
feed:
    path: /feed
    controller: App\Controller\FeedController::index